//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalClinic.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conclusion
    {
        public int Id { get; set; }
        public int MedcardId { get; set; }
        public int AppointmentId { get; set; }
        public string Сomplaints { get; set; }
        public int AnamnesisId { get; set; }
        public int ExaminationId { get; set; }
        public string AdditionalInfo { get; set; }
        public string ConclusionResult { get; set; }
    
        public virtual Anamnesis Anamnesis { get; set; }
        public virtual Appointment Appointment { get; set; }
        public virtual Examination Examination { get; set; }
        public virtual Medcard Medcard { get; set; }
    }
}
